name: github pages

on:
  push:
    branches:
    - master

jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@master
        - run: yarn install vuepress
        - run: yarn run build
    
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v2.5.0

          env:
            ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: docs/.vuepress/dist
