name: github pages

on:
  push:
    branches:
    - master

jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@master
        - run: npm install vuepress
        - run: npm run docs:build
    
        - name: Vuepress deploy
          uses: jenkey2011/vuepress-deploy@1.0.1

          env:
            ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: docs/.vuepress/dist
